version: '3.7'

services:

  geoserver:
    geoserver:
    image: kartoza/geoserver:2.20.1    # see: https://hub.docker.com/r/kartoza/geoserver/ for configuration specifics
    container_name: lata-geoserver
    restart: always

    volumes:
      - ./GSDATA:/opt/geoserver/data_dir # Change the first one to specify local data folder where data will be stored

    links:
      - postgis
    ports:
      - "8801:8080"
    environment:
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=geoserver

  postgis:
    image: postgis/postgis:13-3.2-alpine # see: https://hub.docker.com/r/postgis/postgis for configuration specifics
    container_name: lata-postgis
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
        - ./PGDATA:/var/lib/postgresql/data # Change the first one to specify lockal data folder where data will be stored
    command: -p 5432

    environment:
      - POSTGRES_PASSWORD=Password#123 # PostgreSQL admin password (database is postgis and user is postgis)
    ports:
        - "8802:5432"
